name: watch

on:
  watch:
    types: [ started ]
    branches: [ master ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Greet new watcher
      run: echo Welcome, new watcher!
